/*
 * Copyright (c) 2026. TxnLab Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

package tokenize_test

// Corpus tests for bound version 2.
//
// v2 changes exactly one thing relative to v1: images are priced from their true
// pixel dimensions instead of a flat 2048x2048 fallback. The text term is
// byte-identical to v1. These tests pin both halves of that claim, and — just as
// importantly — record what v2 does NOT fix, so nobody re-derives a false sense
// of safety from a green suite.
//
// HISTORY, because it matters for anyone tempted to tighten the text term: an
// earlier v2 draft replaced the text bound with a character-class run classifier
// whose constants were calibrated against this very corpus, and asserted
// `bound >= real` over the same 40 samples the constants were fitted to. That
// assertion passed by construction and proved nothing. Independent review with a
// holdout set found under-counts up to 3x on punctuation-dense text, mixed-case
// runs, Ethiopic/Georgian/abugida scripts, and integer-heavy tool schemas. If you
// tighten the text term, you need a much broader corpus AND a train/holdout split
// — the assertion below is not sufficient evidence on its own.
//
// Ground truth lives in proto/testdata/tokenize_corpus.json, generated by
// proto/testdata/gen_tokenize_corpus.py (tiktoken + pillow) and checked in, so
// this test needs neither Python nor a tokenizer.
// proto/ts/test/tokenize-corpus.test.ts asserts the identical properties.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/TxnLab/zerosignal/go/tokenize"
)

const (
	corpusDirPath  = "../../testdata/tokenize_corpus"
	corpusFilePath = "../../testdata/tokenize_corpus.json"

	// 2048x2048 high detail — what an image with unknowable dimensions costs,
	// and what v1 charges for every image.
	imageFallbackTokens = 85 + 170*16
)

type corpusSample struct {
	Name       string            `json:"name"`
	BodyBytes  int               `json:"body_bytes"`
	Messages   int               `json:"messages"`
	ImgTokens  uint64            `json:"image_tokens"`
	Tokens     map[string]uint64 `json:"tokens"`
	RealTokens uint64            `json:"real_tokens"`
}

type corpusFile struct {
	Version    int            `json:"version"`
	Comment    string         `json:"comment"`
	Tokenizers []string       `json:"tokenizers"`
	Samples    []corpusSample `json:"samples"`
}

func loadCorpus(t *testing.T) corpusFile {
	t.Helper()
	raw, err := os.ReadFile(corpusFilePath)
	if err != nil {
		t.Fatalf("read corpus fixture (regenerate with proto/testdata/gen_tokenize_corpus.py): %v", err)
	}
	var cf corpusFile
	if err := json.Unmarshal(raw, &cf); err != nil {
		t.Fatalf("parse corpus fixture: %v", err)
	}
	if len(cf.Samples) == 0 {
		t.Fatal("corpus fixture is empty")
	}
	return cf
}

func readSample(t *testing.T, name string) []byte {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(corpusDirPath, name+".json"))
	if err != nil {
		t.Fatalf("read corpus sample %s: %v", name, err)
	}
	return body
}

func isImageSample(name string) bool { return strings.HasPrefix(name, "image_") }

// TestBoundV2MatchesV1OnText is the core invariant of the image-only design:
// for every sample that carries no image, v2 and v1 must be byte-identical.
// If this fails, someone has reintroduced a text-term change — which needs the
// holdout methodology described in this file's header, not a corpus re-run.
func TestBoundV2MatchesV1OnText(t *testing.T) {
	cf := loadCorpus(t)
	checked := 0
	for _, s := range cf.Samples {
		if isImageSample(s.Name) {
			continue
		}
		body := readSample(t, s.Name)
		v1, v2 := tokenize.InputTokenBound(body), tokenize.InputTokenBoundV2(body)
		if v1 != v2 {
			t.Errorf("%s: v2 (%d) diverges from v1 (%d) on a text-only body — v2 must not alter the text term",
				s.Name, v2, v1)
		}
		checked++
	}
	if checked == 0 {
		t.Fatal("no text-only samples found; the corpus can no longer prove the invariant")
	}
}

// TestBoundV2ImagesNeverUnderestimate is the safety property for the half of the
// bound v2 actually changes. Every image-bearing sample must be charged at least
// what a real tokenizer would.
func TestBoundV2ImagesNeverUnderestimate(t *testing.T) {
	cf := loadCorpus(t)
	for _, s := range cf.Samples {
		if !isImageSample(s.Name) {
			continue
		}
		body := readSample(t, s.Name)
		if got := tokenize.InputTokenBoundV2(body); got < s.RealTokens {
			t.Errorf("%s: bound %d < real %d (%.3fx) — the payer under-reserves and the operator eats the difference",
				s.Name, got, s.RealTokens, float64(got)/float64(s.RealTokens))
		}
	}
}

// TestBoundV2ReadsImageDimensions checks the header parser end to end: each
// format's true dimensions must come out of the data URL rather than the
// fallback. GIF is deliberately absent — see sniffImageDims.
func TestBoundV2ReadsImageDimensions(t *testing.T) {
	for _, tc := range []struct {
		sample string
		w, h   int
	}{
		{"image_png_512", 512, 512},
		{"image_png_1024x768", 1024, 768},
		{"image_jpeg_800x600", 800, 600},
		{"image_jpeg_big_exif", 640, 480},
		{"image_webp_vp8x", 1600, 1200},
		{"image_webp_vp8", 900, 700},
		{"image_webp_vp8l", 1280, 720},
	} {
		t.Run(tc.sample, func(t *testing.T) {
			body := readSample(t, tc.sample)
			tilesX, tilesY := (tc.w+511)/512, (tc.h+511)/512
			wantImage := uint64(85 + 170*tilesX*tilesY)

			got := tokenize.InputTokenBoundV2(body)
			if got < wantImage {
				t.Fatalf("bound %d is below the true image cost %d", got, wantImage)
			}
			if wantImage < imageFallbackTokens && got >= imageFallbackTokens {
				t.Fatalf("bound %d still at or above the 2048x2048 fallback %d — dimensions were not read",
					got, imageFallbackTokens)
			}
		})
	}
}

// TestBoundV2FallsBackHigh covers the other direction: when dimensions genuinely
// can't be established, the bound must charge the conservative fallback rather
// than guessing small. GIF is in this set on purpose — its Logical Screen
// Descriptor is payer-controlled and is not the size a decoder reports, so
// trusting it allowed a 36x under-reserve.
func TestBoundV2FallsBackHigh(t *testing.T) {
	for _, sample := range []string{
		"image_remote_url",
		"image_truncated_png",
		"image_garbage_dataurl",
		"image_gif_320x240",
	} {
		t.Run(sample, func(t *testing.T) {
			if got := tokenize.InputTokenBoundV2(readSample(t, sample)); got < imageFallbackTokens {
				t.Fatalf("bound %d is below the %d fallback — an unreadable image must fail HIGH",
					got, imageFallbackTokens)
			}
		})
	}
}

// TestBoundV2FixesLargeImageUnderCount pins the direction of the change that is
// easy to forget: v1's flat 2048x2048 fallback UNDER-charges anything bigger,
// and v2 is the fix. This is why v2 is not uniformly smaller than v1 and why the
// bound version has to be explicit on the wire.
func TestBoundV2FixesLargeImageUnderCount(t *testing.T) {
	// A 4096x4096 image: 8x8 tiles = 85 + 170*64 = 10965 tokens, versus v1's
	// flat 2805.
	body := readSample(t, "image_png_4096")
	v1, v2 := tokenize.InputTokenBound(body), tokenize.InputTokenBoundV2(body)
	const wantImage = 85 + 170*64
	if v1 >= wantImage {
		t.Fatalf("v1 (%d) no longer under-charges a 4096px image; the sample must have changed", v1)
	}
	if v2 < wantImage {
		t.Fatalf("v2 (%d) is below the true 4096px image cost %d", v2, wantImage)
	}
	if v2 <= v1 {
		t.Fatalf("v2 (%d) must exceed v1 (%d) on an image larger than the fallback", v2, v1)
	}
}

// TestV1TextUnderCountsAreKnownAndUnFixed records, rather than fixes, the text
// shapes v1 under-counts. v2 does NOT address them — it only changes the image
// term — and a reader who sees a green suite should not conclude otherwise. If
// one of these ever starts passing it means the text term moved and this file's
// header applies.
func TestV1TextUnderCountsAreKnownAndUnFixed(t *testing.T) {
	cf := loadCorpus(t)
	real := make(map[string]uint64, len(cf.Samples))
	for _, s := range cf.Samples {
		real[s.Name] = s.RealTokens
	}
	for _, name := range []string{
		"adversarial_base64",
		"adversarial_hex",
		"adversarial_uuids",
		"emoji_dense",
		"json_in_content",
	} {
		want, ok := real[name]
		if !ok {
			t.Fatalf("corpus fixture is missing %s", name)
		}
		body := readSample(t, name)
		v1, v2 := tokenize.InputTokenBound(body), tokenize.InputTokenBoundV2(body)
		if v1 >= want {
			t.Errorf("%s: v1 (%d) no longer under-counts real (%d) — update this list", name, v1, want)
		}
		if v2 != v1 {
			t.Errorf("%s: v2 (%d) != v1 (%d); v2 must not touch the text term", name, v2, v1)
		}
	}
}

// TestBoundV2CorpusRatios is informational: it prints the distribution so a
// future change can see where headroom actually sits.
func TestBoundV2CorpusRatios(t *testing.T) {
	cf := loadCorpus(t)
	type row struct {
		name       string
		v1, v2, re uint64
	}
	rows := make([]row, 0, len(cf.Samples))
	for _, s := range cf.Samples {
		body := readSample(t, s.Name)
		rows = append(rows, row{s.Name, tokenize.InputTokenBound(body), tokenize.InputTokenBoundV2(body), s.RealTokens})
	}
	sort.Slice(rows, func(i, j int) bool {
		return float64(rows[i].v2)/float64(rows[i].re) < float64(rows[j].v2)/float64(rows[j].re)
	})
	var b []byte
	b = append(b, fmt.Sprintf("%-30s %8s %8s %8s %8s %8s\n", "sample", "real", "v1", "v1/real", "v2", "v2/real")...)
	for _, r := range rows {
		b = append(b, fmt.Sprintf("%-30s %8d %8d %7.2fx %8d %7.2fx\n",
			r.name, r.re, r.v1, float64(r.v1)/float64(r.re), r.v2, float64(r.v2)/float64(r.re))...)
	}
	t.Log("\n" + string(b))
}

// TestBoundVersionDispatch pins the wire-facing version mapping.
func TestBoundVersionDispatch(t *testing.T) {
	body := readSample(t, "image_png_512")
	v1 := tokenize.InputTokenBound(body)
	v2 := tokenize.InputTokenBoundV2(body)
	if v1 == v2 {
		t.Fatal("sample does not distinguish the two bounds; pick another")
	}
	for _, tc := range []struct {
		version uint8
		want    uint64
	}{
		{0, v1}, // unspecified on the wire => v1
		{tokenize.BoundVersion1, v1},
		{tokenize.BoundVersion2, v2},
		{99, v1}, // unknown => v1's text term, never under-charge
	} {
		if got := tokenize.InputTokenBoundVersion(body, tc.version); got != tc.want {
			t.Errorf("InputTokenBoundVersion(_, %d) = %d, want %d", tc.version, got, tc.want)
		}
	}
	if !tokenize.SupportedBoundVersion(0) || !tokenize.SupportedBoundVersion(1) || !tokenize.SupportedBoundVersion(2) {
		t.Error("versions 0/1/2 must all be supported")
	}
	if tokenize.SupportedBoundVersion(3) {
		t.Error("version 3 is not implemented and must not report as supported")
	}
}

// TestV1DivergesOnOutOfRangeDimension documents a PRE-EXISTING v1 defect that
// the adversarial vectors surfaced, and records why it is not being fixed here.
//
// v1 has no clamp on a caller-declared width/height, so `"width": 1e19` runs
// straight into its tile multiplication. Go converts the float to int first —
// implementation-defined for out-of-range values, saturating on arm64 and
// wrapping on amd64 — while TS multiplies in float64 and reaches ~6.5e34. The
// two implementations therefore disagree, and have since v1 shipped.
//
// It is left alone on purpose: v1 is the compatibility floor every pre-9.2 node
// and caller computes, and changing it would make a new build disagree with a
// deployed one on inputs where they currently agree. v2 fixes it properly by
// range-checking before conversion and clamping to imageMaxDimensionPx, which
// is what this test pins.
func TestV1DivergesOnOutOfRangeDimension(t *testing.T) {
	body := []byte(`{"model":"m","messages":[{"role":"user","content":[{"type":"image_url",` +
		`"width":1e19,"height":1e19,"image_url":{"url":"https://x/y.png"}}]}]}`)

	// v2 is well-defined: clamped to 16384x16384 = 32x32 tiles.
	const wantV2Image = 85 + 170*32*32
	v2 := tokenize.InputTokenBoundV2(body)
	if v2 < wantV2Image {
		t.Fatalf("v2 = %d, want at least the clamped image cost %d", v2, wantV2Image)
	}
	// And it must not have exploded past the clamp.
	if v2 > wantV2Image+1000 {
		t.Fatalf("v2 = %d is far above the clamped cost %d — the clamp is not being applied",
			v2, wantV2Image)
	}

	// v1 is deliberately NOT asserted on by magnitude: its value here is the
	// defect. Observed while writing this: 180 on darwin/arm64 (the int64 tile
	// product wraps) and ~6.5e34 in TypeScript (float64 multiplication, no
	// wrap). Pinning either would make this test itself architecture-dependent,
	// which is the very thing being documented. Asserting they DIFFER is the
	// stable, meaningful check.
	if v1 := tokenize.InputTokenBound(body); v1 == v2 {
		t.Fatalf("v1 == v2 == %d — v1 appears to have gained a clamp; if that was "+
			"deliberate, the compatibility floor changed and this test should be revisited", v1)
	}
}
