/*
 * Copyright (c) 2026. TxnLab Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

// Wire-protocol constants. Changing any of these is a wire-breaking
// change — keep in lockstep with proto/go/wire/envelope.go and
// proto/SPEC.md. The protocol is still in active development; wire shape
// is not yet frozen.

export const ENCRYPTED_CONTENT_TYPE = 'application/vnd.zs+json'
export const RESPONSE_KEY_HEADER = 'X-Zs-Response-Key'
export const RECEIPT_HEADER = 'X-Zs-Receipt'
export const SETTLE_GROUP_HEADER = 'X-Zs-Settle-Group'

export const STREAM_EVENT_MARKER = 'zs'
export const STREAM_EVENT_RECEIPT = 'zs-receipt'
export const STREAM_EVENT_SETTLE_GROUP = 'zs-settle-group'

// Sealed-metadata names. Each names one piece of post-response metadata
// sealed under K_response with buildHeaderAAD, so a relay forwarding the
// response cannot read it. The name is bound into the AAD, which is what
// stops a receipt ciphertext from being replayed as a settle group.
//
// Both carry payer-linkable data: the settle group's payer-ack template
// names the payer address outright, and the receipt carries ticket_id, which
// resolves to TicketRecord.payer on chain. See SPEC.md § 3f.
export const SEALED_HEADER_RECEIPT = 'receipt'
export const SEALED_HEADER_SETTLE_GROUP = 'settle-group'

// Symmetric key used for AEAD-sealing response payloads. Generated by
// the node, wrapped to the proxy's ephemeral X25519 recipient via age,
// and surfaced in the X-Zs-Response-Key header (and the reserve
// response's wrapped_response_key field).
export const RESPONSE_KEY_SIZE = 32

// chacha20poly1305 IETF nonce size.
export const NONCE_SIZE = 12

// chacha20poly1305 IETF tag size.
export const POLY1305_TAG_SIZE = 16

// Transport-privacy (single-hop operator-as-relay) constants. Mirror of
// proto/go/wire/envelope.go. RELAY_PATH is the route every node exposes to
// forward an inner request to another operator on a client's behalf, hiding
// the client's IP from the target. The request stays sealed to the target's
// age key — these headers carry only routing metadata. See SPEC.md
// "Transport bindings".
export const RELAY_PATH = '/v1/zs/relay'
export const RELAY_TARGET_HEADER = 'X-Zs-Relay-Target'
// Node id within the operator named by RELAY_TARGET_HEADER (operator/node
// split: a base URL belongs to a node, so the relay needs both ids).
export const RELAY_TARGET_NODE_HEADER = 'X-Zs-Relay-Target-Node'
export const RELAY_PATH_HEADER = 'X-Zs-Relay-Path'
export const RELAY_METHOD_HEADER = 'X-Zs-Relay-Method'

// RELAY_HOP_HEADER is the one RESPONSE-side relay header (every other
// RELAY_*_HEADER above rides the request). A relaying node sets it on EVERY
// response it produces on RELAY_PATH — as the first statement of its handler,
// before any validation or forwarding — and skips this key when copying the
// target's headers back, so a target can neither forge nor erase it.
//
// It exists because two very different failures used to be byte-identical to
// the caller: the relay's own CDN / ingress answering a code-less 504 (the
// relay's handler NEVER RAN — we were blocked at its front door), versus the
// relay running, forwarding, and copying the TARGET's code-less 504 back
// verbatim. Presence means exactly "the zs relay handler ran"; the inferences
// a caller draws are in narrowRelayed, gated on setsRelayHopHeader.
//
// BROWSER TRAP: a response header is unreadable from JS unless the node lists
// it in Access-Control-Expose-Headers. If it is missing there, every relayed
// response reads as "marker absent" — which does not degrade gracefully, it
// INVERTS, blaming every relay for every code-less 5xx.
export const RELAY_HOP_HEADER = 'X-Zs-Relay-Hop'
// The only value RELAY_HOP_HEADER carries. The signal is presence, not
// content; the value is a reserved generation marker.
export const RELAY_HOP_HEADER_VALUE = '1'
